/*
 * tlins_DeviceWebSerciceErrors.hpp
 *
 *  Created on: 15-05-2012
 *      Author: jacek
 */

#ifndef TLINS_DEVICEWEBSERCICEERRORS_HPP_
#define TLINS_DEVICEWEBSERCICEERRORS_HPP_

#define TLINS_WS_OK 0

#define TLINS_WS_ERROR_UNKNOW_REQUEST_MODE (-1000001)
#define TLINS_WS_ERROR_UNKNOW_CTRL_REQUEST_MODE (-1000002)
#define TLINS_WS_ERROR_UNKNOW_REQUEST_DIRECTION (-1000003)
#define TLINS_WS_ERROR_ENQUEU_REQUEST (-1000004)

#endif /* TLINS_DEVICEWEBSERCICEERRORS_HPP_ */
