#!/bin/sh

export LD_LIBRARY_PATH=${HOME}/development/project/external/release/lib:${HOME}/development/project/external/release/lib64:${LD_LIBRARY_PATH}
rm CMakeLists.txt 2> /dev/null
ln -s CMakeLists-arm.txt CMakeLists.txt
cmake .
make -j18

if [ ${?} != 0 ]
then
        exit 1
else
        exit 0
fi
